version: '2.2'

services:

  klimaatatlas-geoserver:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - /119-storage-d4/klimaatatlas-geoserver-data-dir:/opt/geoserver_data

# TODO: add logfile-to-ELK docker
